"""
recovery_grid.py
=================

THE fix for the flaw in compare.py's original design: that comparison
generated ONE synthetic dataset from Model A's generative process and
asked all seven models to predict it -- which was never a fair test
for Model B (it was being scored on data it wasn't built to generate),
and it couldn't distinguish "Model B's sampler is broken" from "Model
B is just the wrong model for this particular data."

WHAT THIS DOES INSTEAD: a model-recovery / confusion matrix (standard
practice in computational modelling, e.g. Wilson & Collins 2019 "Ten
simple rules for computational modeling of behavioral data"). Seven
generators x seven fitters = 49 cells (Standard included as its own
generator -- see below; an earlier version of this file wrongly
excluded it as "nested inside A-B1", which is true in principle but
meant the single most basic sanity check, "can the harness recover
the simplest possible ground truth at all", was never actually run).
The diagonal (fit model X on data generated by X) is the direct
answer to today's question: can the sampler recover known ground truth
from its OWN model, independent of any generator/fitter mismatch? The
off-diagonal cells show how much models can mimic each other's data,
which is exactly the information WAIC/LOO needs context from.

NAMING: this file uses "A-B1"/"A-B2"/"B-Matern-B1"/... throughout, NOT
the equations doc's "A-C1"/"A-C2"/"B-C1"/"B-C2" naming. That's a real
naming drift between the doc and the code (bayesian_mixed_trf.py's
variant strings are literally "A-B1"/"A-B2", and fit_bayesian_mixed_trf
raises ValueError on anything else) -- worth reconciling in the doc
at some point, but this file matches the CODE's naming since it calls
that code directly.

GENERATORS: six generators reuse existing, already self-tested code
(nothing here duplicates a generative process, only wires existing
pieces together), plus a seventh added for completeness after review:
  Standard    : ground_truth.py's make_stage1_static -- beta=0, NO
                hierarchy (a single shared h(tau) for every unit).
                This is not a stylistic placeholder: it's the actual
                null-model ground truth Standard's own ridge fit
                assumes, and Standard->Standard is the cheapest, most
                basic sanity check in the whole grid -- if design
                matrix construction, SNR scaling, or the ridge fit
                itself were subtly wrong, THIS is the cell that would
                catch it, before blaming anything model-specific.
  A-B1        : make_stage2_amplitude_only (beta_j = gain*mu_j) + hierarchy.
  A-B2        : make_stage3_full_modulation (beta_j free per basis function)
                + hierarchy.
  B-Matern-B1 : ground_truth_gp.py's make_stage3_full_modulation,
                kernel_type="matern52", delta=None (B1) + hierarchy.
  B-Matern-B2 : same, delta/gamma set (B2, added in the previous session).
  B-SE-B1     : same as B-Matern-B1, kernel_type="squared_exponential".
  B-SE-B2     : same as B-Matern-B2, kernel_type="squared_exponential".

FITTERS: exactly compare.py's seven fit_predict_* functions, imported
and reused directly, not reimplemented -- the grid's whole point is to
stress-test those exact fitters on harder-to-mismatch data, not to
introduce a second parallel fitting implementation that could itself
drift from compare.py's.

SCALE: a full 42-cell grid at compare.py's production settings
(n_patients=4, n_electrodes=3, draws=500, tune=1000, chains=4) would
take on the order of a full day, given individual Bayesian fits were
already taking 15-80 minutes each on the shared-dataset run, and some
(SE-B1/B2) took 4900-9200s (over an hour) each. Default here is a much
smaller PILOT scale (fewer patients/electrodes/lags/draws/tune) so the
whole grid finishes in a practical amount of time and tells you, TODAY,
whether the funnel problem is generator/fitter-mismatch-specific or
present even on each model's own home turf. Bump to scale="full" (or
pass explicit sizes) once the pilot grid tells you which cells are
worth the expensive rerun.

CHECKPOINTING: each cell is fit, scored, and immediately written to
results_path as JSON before moving to the next cell. Re-running this
script with the same results_path picks up where it left off (skips
any (generator, fitter) pair already present) rather than restarting
the whole grid -- necessary given how likely a 42-cell run is to get
interrupted at full scale.
"""

from __future__ import annotations

import json
import os
import time
import numpy as np

from basis.basis_functions import make_raised_cosine_basis
from utils.design_matrix import build_design_matrix, build_raw_lag_design_matrix, expand_word_level_to_samples
from data.simulate import make_word_stream
from metrics import train_test_split_contiguous

import ground_truth as gt_a
import ground_truth_gp as gt_b

from compare import (
    fit_predict_model1_standard,
    fit_predict_model_A,
    fit_predict_model_B,
)


# ============================================================================
# 1. Generator / fitter registries
# ============================================================================

GENERATOR_NAMES = ["Standard", "A-B1", "A-B2", "B-Matern-B1", "B-Matern-B2", "B-SE-B1", "B-SE-B2"]
FITTER_NAMES = ["Standard", "A-B1", "A-B2", "B-Matern-B1", "B-Matern-B2", "B-SE-B1", "B-SE-B2"]

# Fixed, name-keyed seed offsets -- NOT list position. Bug found after adding
# "Standard" as a 7th generator: the dataset seed used to be `seed + gi`
# where gi was each generator's INDEX in GENERATOR_NAMES. Prepending
# "Standard" silently shifted every other generator's index by +1, so a
# "before/after" comparison across two runs (e.g. checking whether a bug
# fix in the fitting code changed a cell's result) was secretly ALSO
# comparing against different underlying synthetic data -- a real
# confound, not just a cosmetic one. These offsets match the ORIGINAL
# six-generator ordering (before Standard existed) exactly, so every
# already-collected result for those six generators stays reproducible
# and comparable; Standard gets a new offset appended at the end rather
# than reusing 0 and bumping everyone else again.
_GENERATOR_SEED_OFFSET = {
    "A-B1": 0, "A-B2": 1, "B-Matern-B1": 2, "B-Matern-B2": 3,
    "B-SE-B1": 4, "B-SE-B2": 5, "Standard": 6,
}

_ARRAY_KEYS = ("S0_basis", "S1_basis", "S0_raw", "S1_raw", "r")


def _family_of(generator_name: str) -> str:
    """'basis' -> ground_truth.py (mu/beta live on basis coefficients),
    covers Standard (non-hierarchical) and A-B1/A-B2 (hierarchical).
    'gp' -> ground_truth_gp.py (h0/h1 live directly on the lag grid)."""
    return "basis" if (generator_name == "Standard" or generator_name.startswith("A-")) else "gp"


def build_dataset_from_generator(
    generator_name: str,
    basis,
    taus: np.ndarray,
    n_patients: int,
    n_electrodes: int,
    n_times: int,
    dt: float,
    snr_target: float,
    seed: int,
    return_ground_truth: bool = False,
):
    """
    Builds ONE synthetic dataset from the named generator's own
    generative process, but returns BOTH basis-projected and raw-lag
    design matrices for every unit regardless of which family
    generated the response -- every fitter needs its native matrix
    type no matter which generator produced the underlying data, which
    is the mechanism that makes cross-fitting possible at all.

    return_ground_truth : if True, also includes the internal `gt`
        object (GroundTruthEffects for Model A, GroundTruthGP for
        Model B) in the returned dict under "ground_truth". Needed by
        anything that wants the TRUE per-unit shape after the fact
        (e.g. plot_diagonal_shapes.py) -- get it from HERE, not by
        reconstructing a separately-seeded copy: ground_truth_gp.py's
        shape_for() is a lazy, RNG-state-dependent draw (only consumes
        RNG the first time a given unit is requested), and this
        function's own per-unit loop below already advances the RNG
        (stimulus, word stream) before first calling shape_for for
        each unit -- a fresh reconstruction elsewhere that calls
        shape_for without first replaying those exact draws will
        silently draw a DIFFERENT, unrelated h0/h1 and call it "true".
        Default False keeps this a no-op for every existing caller.
    """
    rng = np.random.default_rng(seed)
    family = _family_of(generator_name)

    if generator_name == "Standard":
        # deliberately NOT hierarchical: one shared h(tau), beta=0, no
        # surprisal effect -- the actual null model Standard's own
        # closed-form ridge fit assumes, not a placeholder
        gt = gt_a.make_stage1_static(basis, rng)
    elif generator_name == "A-B1":
        base = gt_a.make_stage2_amplitude_only(basis, rng, gain=-0.3)
        gt = gt_a.add_hierarchical_random_effects(base, n_patients, n_electrodes, rng)
    elif generator_name == "A-B2":
        base = gt_a.make_stage3_full_modulation(basis, rng)
        gt = gt_a.add_hierarchical_random_effects(base, n_patients, n_electrodes, rng)
    elif generator_name in ("B-Matern-B1", "B-SE-B1", "B-Matern-B2", "B-SE-B2"):
        kernel_type = "matern52" if "Matern" in generator_name else "squared_exponential"
        is_b2 = generator_name.endswith("B2")
        base = gt_b.make_stage3_full_modulation(
            kernel_type, taus, ell0=100.0, sigma0=2.0, ell1=30.0, sigma1=1.5,
            delta=(-0.3 if is_b2 else None), gamma=(0.0 if is_b2 else None),
        )
        gt = gt_b.add_hierarchical_random_effects(base, n_patients, n_electrodes, rng)
    else:
        raise ValueError(f"unknown generator {generator_name!r}")

    S0_basis_all, S1_basis_all = [], []
    S0_raw_all, S1_raw_all = [], []
    r_all = []
    patient_idx = []
    unit_mean_surp = []

    for p in range(n_patients):
        for e in range(n_electrodes):
            stimulus = rng.normal(0, 1, size=n_times)
            word_onsets, word_surp = make_word_stream(n_times, dt, words_per_second=3.0, rng=rng)
            surp_at_t = expand_word_level_to_samples(n_times, dt, word_onsets, word_surp)
            unit_surp_mean = float(word_surp.mean())

            design_basis = build_design_matrix(stimulus, surp_at_t, basis, dt)
            design_raw = build_raw_lag_design_matrix(stimulus, surp_at_t, taus, dt)

            if family == "basis":
                mu_eff, beta_eff = gt.weight_for(patient=p, electrode=e)
                signal = design_basis.S0 @ mu_eff + design_basis.S1 @ beta_eff
            else:  # family == "gp"
                h0, h1 = gt.shape_for(patient=p, electrode=e, rng=rng, surp=unit_surp_mean)
                signal = design_raw.S0 @ h0 + design_raw.S1 @ h1

            sigma_noise = signal.std() / snr_target if signal.std() > 1e-10 else 0.1
            noise = rng.normal(0, sigma_noise, size=n_times)
            r = signal + noise

            S0_basis_all.append(design_basis.S0); S1_basis_all.append(design_basis.S1)
            S0_raw_all.append(design_raw.S0); S1_raw_all.append(design_raw.S1)
            r_all.append(r)
            patient_idx.append(p)
            unit_mean_surp.append(unit_surp_mean)

    result = {
        "S0_basis": np.array(S0_basis_all), "S1_basis": np.array(S1_basis_all),
        "S0_raw": np.array(S0_raw_all), "S1_raw": np.array(S1_raw_all),
        "r": np.array(r_all),
        "patient_idx": np.array(patient_idx),
        "unit_mean_surp": np.array(unit_mean_surp),
        "n_units": n_patients * n_electrodes,
        "n_times": n_times,
    }
    if return_ground_truth:
        result["ground_truth"] = gt
    return result


def split_train_test(data: dict, test_fraction: float = 0.2):
    """Same contiguous split as compare.py's split_train_test, applied
    to this module's dataset dict -- deliberately NOT importing
    compare.py's version, since that one also expects "basis"/"taus"/
    "dt" keys this dict doesn't carry (those are threaded separately
    here); duplicating this ~6-line split is lower-risk than reshaping
    this dict to match compare.py's exactly."""
    train_idx, test_idx = train_test_split_contiguous(data["n_times"], test_fraction=test_fraction)
    train = {k: data[k][:, train_idx, :] if data[k].ndim == 3 else data[k][:, train_idx] for k in _ARRAY_KEYS}
    test = {k: data[k][:, test_idx, :] if data[k].ndim == 3 else data[k][:, test_idx] for k in _ARRAY_KEYS}
    return train, test


# ============================================================================
# 2. One cell: fit `fitter_name` to data from `generator_name`
# ============================================================================

def fit_one_cell(fitter_name, train, test, patient_idx, taus, unit_mean_surp, n_basis, fit_kwargs_A, fit_kwargs_B, gt=None, basis=None):
    """
    gt : the TRUE generator's ground-truth object (from
    build_dataset_from_generator's return_ground_truth=True). Passed
    through to every fitter so each cell -- diagonal AND off-diagonal
    -- also reports a shape-recovery metric (true vs. recovered h(tau)
    for unit 0), not just held-out r and convergence diagnostics. This
    directly answers "the model predicts well, but did it recover the
    right SHAPE" -- exactly the gap the shape-comparison plots exposed
    that r/rhat/LOO alone never would have caught.
    """
    if fitter_name == "Standard":
        r, shape_metrics = fit_predict_model1_standard(train, test, taus, gt=gt, basis=basis)
        return r, None, shape_metrics
    if fitter_name in ("A-B1", "A-B2"):
        return fit_predict_model_A(
            train, test, patient_idx, n_basis, fitter_name,
            gt=gt, basis=basis, taus=taus, **fit_kwargs_A,
        )
    kernel_type = "matern52" if "Matern" in fitter_name else "squared_exponential"
    surprisal_in_kernel = fitter_name.endswith("B2")
    return fit_predict_model_B(
        train, test, patient_idx, taus, unit_mean_surp, kernel_type, surprisal_in_kernel,
        gt=gt, **fit_kwargs_B,
    )


# ============================================================================
# 3. The grid, with checkpointing
# ============================================================================

def run_recovery_grid(
    scale: str = "pilot",
    n_patients: int | None = None,
    n_electrodes: int | None = None,
    n_times: int | None = None,
    n_basis: int | None = None,
    tau_max: float | None = None,
    dt: float = 10.0,
    draws: int | None = None,
    tune: int | None = None,
    chains: int | None = None,
    results_path: str = "figures/recovery_grid_results.json",
    seed: int = 0,
    only_diagonal: bool = False,
    only_cells: list[tuple[str, str]] | None = None,
    task_id: int | None = None,
    n_tasks: int | None = None,
    cores: int | None = None,
):
    """
    scale="pilot" (default): small enough to finish the WHOLE 42-cell
    grid in a practical amount of time on a laptop -- meant to answer
    "does self-recovery work at all, architecturally" TODAY, not to be
    the final production numbers. scale="full": compare.py's original
    production settings, applied uniformly across all 42 cells --
    expect this to take a long time (likely most of a day); consider
    running specific cells you've already decided are worth it rather
    than the whole grid at once, unless you can leave it running
    overnight. Any explicitly-passed size argument overrides the scale
    preset.

    only_diagonal : if True, only fit the 6 (generator == fitter)
        self-recovery cells -- the direct answer to "can each model's
        sampler recover its OWN known ground truth", the cheapest
        meaningful subset when you want to bump chains/draws/tune
        without paying for all 42 cells. Takes priority over
        only_cells if both are given.
    only_cells : explicit list of (generator_name, fitter_name) pairs
        to run, e.g. [("B-SE-B1", "B-SE-B1")] to re-check one specific
        cell (say, at chains=4) after a pilot run flagged it.
    task_id, n_tasks : Slurm/SGE array-job slicing over CELLS (applied
        AFTER only_diagonal/only_cells filtering) -- this worker
        handles cells[task_id::n_tasks]. IMPORTANT, unlike
        identifiability_study.py: this file's checkpoint is one JSON
        dict, not append-only JSON-lines, so it is NOT safe for
        multiple array workers to share the same results_path
        concurrently (a read-modify-write race would silently drop
        results). Give each array task its OWN results_path (e.g.
        results_task${SLURM_ARRAY_TASK_ID}.json) and merge them
        afterward with merge_recovery_results.py.
    cores : parallel chains per fit; None -> cores=chains (see
        bayesian_gp_trf.py/bayesian_mixed_trf.py's own cores docstring
        -- this used to be hardcoded to 1, wasting a shared multi-core
        node's idle capacity on every single fit).
    """
    presets = {
        "pilot": dict(n_patients=2, n_electrodes=2, n_times=400, n_basis=5,
                      tau_max=100.0, draws=150, tune=300, chains=2),
        "full":  dict(n_patients=4, n_electrodes=3, n_times=1000, n_basis=6,
                       tau_max=200.0, draws=500, tune=1000, chains=4),
    }
    p = presets[scale]
    n_patients = n_patients if n_patients is not None else p["n_patients"]
    n_electrodes = n_electrodes if n_electrodes is not None else p["n_electrodes"]
    n_times = n_times if n_times is not None else p["n_times"]
    n_basis = n_basis if n_basis is not None else p["n_basis"]
    tau_max = tau_max if tau_max is not None else p["tau_max"]
    draws = draws if draws is not None else p["draws"]
    tune = tune if tune is not None else p["tune"]
    chains = chains if chains is not None else p["chains"]

    if only_diagonal:
        cell_filter = set((g, g) for g in GENERATOR_NAMES)
    elif only_cells is not None:
        cell_filter = set(only_cells)
    else:
        cell_filter = None  # run everything

    all_candidate_cells = [
        (g, f) for g in GENERATOR_NAMES for f in FITTER_NAMES
        if cell_filter is None or (g, f) in cell_filter
    ]
    my_cells = set(all_candidate_cells[task_id::n_tasks]) if (task_id is not None and n_tasks is not None) else set(all_candidate_cells)
    if task_id is not None and n_tasks is not None:
        if not (0 <= task_id < n_tasks):
            raise ValueError(f"task_id ({task_id}) must be in [0, n_tasks={n_tasks})")

    print(f"Recovery grid: scale={scale!r}, n_patients={n_patients}, n_electrodes={n_electrodes}, "
          f"n_times={n_times}, n_basis={n_basis}, tau_max={tau_max}, draws={draws}, tune={tune}, chains={chains}")
    if cell_filter is not None:
        print(f"Restricted to {len(cell_filter)} candidate cell(s): {sorted(cell_filter)}")
    if task_id is not None and n_tasks is not None:
        print(f"Array-job slicing: task_id={task_id}/{n_tasks} -> {len(my_cells)}/{len(all_candidate_cells)} "
              f"candidate cell(s) assigned to this worker: {sorted(my_cells)}")
    print(f"Checkpointing to {results_path} -- safe to Ctrl+C and re-run, already-completed cells are skipped.\n")

    basis = make_raised_cosine_basis(n_basis=n_basis, tau_max=tau_max, c=5.0)
    n_lags = int(np.floor(tau_max / dt)) + 1
    taus = np.arange(n_lags) * dt

    fit_kwargs_A = dict(draws=draws, tune=tune, chains=chains, cores=cores,
                         target_accept=0.99, max_treedepth=14, seed=seed)
    fit_kwargs_B = dict(draws=draws, tune=tune, chains=chains, cores=cores,
                         target_accept=0.99, max_treedepth=14, seed=seed)

    os.makedirs(os.path.dirname(results_path), exist_ok=True)
    if os.path.exists(results_path):
        with open(results_path) as f:
            results = json.load(f)
        print(f"Loaded {len(results)} already-completed cell(s) from {results_path}.")
    else:
        results = {}

    total = len(my_cells)
    cell_counter = 0
    done_this_run = 0
    for gi, generator_name in enumerate(GENERATOR_NAMES):
        # skip building this generator's dataset entirely if this worker
        # has no assigned cells for it -- matters once task_id/n_tasks
        # slicing is in play, otherwise every array worker would pay for
        # all 7 dataset builds just to fit the 1-2 cells it actually owns
        if not any(g == generator_name for g, f in my_cells):
            continue

        # one dataset per generator, shared across all seven fitters (fair:
        # every fitter sees the exact same held-out data for this generator)
        # return_ground_truth=True: needed so every cell (not just the ones
        # someone remembers to check by hand) reports a shape-recovery
        # metric alongside r/diagnostics.
        data = build_dataset_from_generator(
            generator_name, basis, taus, n_patients, n_electrodes, n_times, dt,
            snr_target=5.0, seed=seed + _GENERATOR_SEED_OFFSET[generator_name],
            return_ground_truth=True,
        )
        train, test = split_train_test(data)
        patient_idx = data["patient_idx"]
        unit_mean_surp = data["unit_mean_surp"]
        gt = data["ground_truth"]

        for fi, fitter_name in enumerate(FITTER_NAMES):
            if (generator_name, fitter_name) not in my_cells:
                continue
            key = f"{generator_name} -> {fitter_name}"
            cell_counter += 1
            cell_idx = cell_counter
            if key in results:
                print(f"[{cell_idx}/{total}] {key}: already done (r={results[key].get('r', float('nan')):.4f}), skipping.")
                continue

            print(f"[{cell_idx}/{total}] {key} ...", flush=True)
            t0 = time.time()
            try:
                r, diag, shape_metrics = fit_one_cell(
                    fitter_name, train, test, patient_idx, taus, unit_mean_surp,
                    n_basis, fit_kwargs_A, fit_kwargs_B, gt=gt, basis=basis,
                )
                elapsed = time.time() - t0
                results[key] = {
                    "generator": generator_name, "fitter": fitter_name,
                    "r": float(r), "diagnostics": diag, "shape_recovery": shape_metrics,
                    "elapsed_s": elapsed, "is_diagonal": generator_name == fitter_name,
                }
                flag = ""
                if diag is not None and (diag["max_rhat"] > 1.01 or diag["n_divergences"] > 0):
                    flag = "  <-- NOT CONVERGED"
                shape_str = ""
                if shape_metrics is not None:
                    shape_str = f"  shape_corr={shape_metrics['correlation']:.3f}"
                print(f"    r={r:.4f}  ({elapsed:.0f}s){flag}{shape_str}")
            except Exception as exc:
                results[key] = {
                    "generator": generator_name, "fitter": fitter_name,
                    "error": str(exc), "elapsed_s": time.time() - t0,
                    "is_diagonal": generator_name == fitter_name,
                }
                print(f"    FAILED: {exc}")

            # checkpoint after EVERY cell, not just at the end
            with open(results_path, "w") as f:
                json.dump(results, f, indent=2)
            done_this_run += 1

    print(f"\nDone. {done_this_run} cell(s) fit this run, {len(results)}/{total} total complete.")
    print(f"Results saved to {results_path}. Run plot_recovery_grid.py to visualise.")
    return results


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--scale", choices=["pilot", "full"], default="pilot")
    parser.add_argument("--results-path", default="figures/recovery_grid_results.json")
    parser.add_argument("--chains", type=int, default=None)
    parser.add_argument("--draws", type=int, default=None)
    parser.add_argument("--tune", type=int, default=None)
    parser.add_argument("--only-diagonal", action="store_true",
                         help="Only fit the 6 self-recovery (generator==fitter) cells.")
    parser.add_argument("--only-cells", nargs="+", default=None,
                         help="One or more GENERATOR:FITTER pairs to run, e.g. "
                              "--only-cells B-SE-B1:B-SE-B1 B-SE-B2:B-SE-B2 "
                              "(colon-separated, not comma -- comma would need shell "
                              "quoting gymnastics argparse doesn't handle cleanly here).")
    parser.add_argument("--n-patients", type=int, default=None)
    parser.add_argument("--n-electrodes", type=int, default=None)
    parser.add_argument("--n-times", type=int, default=None)
    parser.add_argument("--n-basis", type=int, default=None)
    parser.add_argument("--tau-max", type=float, default=None)
    parser.add_argument("--task-id", type=int, default=None,
                         help="Slurm/SGE array-job slicing over CELLS. This worker handles "
                              "cells[task_id::n_tasks]. NOTE: give each array task its OWN "
                              "--results-path -- this file's checkpoint is a single JSON dict, "
                              "not append-only, so concurrent workers sharing one path would race.")
    parser.add_argument("--n-tasks", type=int, default=None)
    parser.add_argument("--cores", type=int, default=None,
                         help="Parallel chains per fit. None -> cores=chains.")
    args = parser.parse_args()

    only_cells = None
    if args.only_cells is not None:
        only_cells = []
        for pair in args.only_cells:
            if ":" not in pair:
                parser.error(f"--only-cells expects GENERATOR:FITTER (colon-separated), got {pair!r}")
            gen, fit = pair.split(":", 1)
            if gen not in GENERATOR_NAMES:
                parser.error(f"unknown generator {gen!r}; must be one of {GENERATOR_NAMES}")
            if fit not in FITTER_NAMES:
                parser.error(f"unknown fitter {fit!r}; must be one of {FITTER_NAMES}")
            only_cells.append((gen, fit))

    run_recovery_grid(
        scale=args.scale, results_path=args.results_path,
        chains=args.chains, draws=args.draws, tune=args.tune,
        n_patients=args.n_patients, n_electrodes=args.n_electrodes,
        n_times=args.n_times, n_basis=args.n_basis, tau_max=args.tau_max,
        only_diagonal=args.only_diagonal, only_cells=only_cells,
        task_id=args.task_id, n_tasks=args.n_tasks, cores=args.cores,
    )